package com.coship.ott.constant;

public class UdrmDefine {
	//UDRMϵͳ����ֵ����
		public static final int UDRM_ERROR_OK = 0; //Ok \ �ɹ�
		public static final int UDRM_ERROR_UNKNOWN_ERROR = -1; //Unknown error \ δ֪����
		public static final int UDRM_ERROR_ENCRYPT_FAILED = -2; //Encrypt failed \ ���ܴ���
		public static final int UDRM_ERROR_DECRYPT_FAILED = -3; //Decrypt failed \ ���ܴ���
		public static final int UDRM_ERROR_WAIT_TIMEOUT = -4; //Time out ocour when call function \ �ȴ�ʱ
		public static final int UDRM_ERROR_INVALID_ARGUMENT = -5; //The argument passed to function is invalid \ ������Ч
		public static final int UDRM_ERROR_NOT_ENOUGH_MEMORY = -6; //Memory allocated by called function fail \ �ڴ治��
		public static final int UDRM_ERROR_NOT_ENOUGH_RESOURCE = -7; //Resource such as some hardware is not enough \ ��Դ����
		public static final int UDRM_ERROR_NOT_SUPPORT = -8; //This function is not support now \ ���ܲ�֧��
		public static final int UDRM_ERROR_DEVICE_NOT_PRESENT = -9; //The device is not present \ �豸������
		public static final int UDRM_ERROR_NOT_ENOUGH_BUFFER = -10; //Buffer is not enough \ �������
		public static final int UDRM_ERROR_CONNNECT_FAILED = -11; //Connect server failed \ ����ʧ��
		public static final int UDRM_ERROR_UDRMCLIENT_NOT_EXIST = -12; //DRM client not exist \ DRM�豸������
		public static final int UDRM_ERROR_CONTENT_NOT_EXIST = -13; //DRM content not exist \ ���ݲ�����
		public static final int UDRM_ERROR_CREDIT_NOT_ENOUGH = -14; //Credit not enough \ �ʽ���
		public static final int UDRM_ERROR_SYSTEM_BUSY = -15; //System is busy \ ϵͳæ
		public static final int UDRM_ERROR_DEVICE_INVALID = -16; //Device is invalid \ �豸��Ч
		public static final int UDRM_ERROR_HMAC_ERROR = -17; //HMAC error \ У�����
		public static final int UDRM_ERROR_DICTATE_INVALID = -18; //Dictate is invalid \ ָ�����
		public static final int UDRM_ERROR_SYSTEM_ERROR = -19; //System error \ ϵͳ����
		public static final int UDRM_ERROR_TYPE_ERROR = -20; //Type is error \ ���ʹ���
		public static final int UDRM_ERROR_MESSAGE_ERROR = -21; //Message is error \ ��Ϣ����
		public static final int UDRM_ERROR_INDEX_ERROR = -22; //Index is error \ �������
		public static final int UDRM_ERROR_DEVICE_CERT_EXIST = -23; //The cert of DRM exist \ �豸֤���Ѵ���
		public static final int UDRM_ERROR_DEVICE_CERT_NOT_MATCH = -24; //The cert is not match of DRM Cert \ �豸֤�鲻ƥ��
		public static final int UDRM_ERROR_CERT_OK = -25; //Cert is OK \ ֤����
		public static final int UDRM_ERROR_CERT_NOT_EXIST = -26; //Cert is not exist \ ֤�鲻����
		public static final int UDRM_ERROR_CERT_NOT_ISSUE = -27; //Cert is not issue \ ֤��δ�䷢
		public static final int UDRM_ERROR_CERT_SUSPEND = -28; //Cert is suspend \ ֤�鱻ͣ��
		public static final int UDRM_ERROR_CERT_FORBID = -29; //Cert is forbid \ ֤�鱻����
		public static final int UDRM_ERROR_CERT_UPDATE = -30; //Cert need update \ ֤�������
		public static final int UDRM_ERROR_CERT_REVOKE = -31; //Cert is revoke \ ֤���ѳ���
		public static final int UDRM_ERROR_CERT_EXPIRATION = -32; //Cert is expiration \ ֤���ѹ���
		public static final int UDRM_ERROR_CERT_VERIFY_ERROR = -33; //Cert varify error \ ֤��У��ʧ��
		public static final int UDRM_ERROR_MANUAL_SETUP = -34; //It must manual setup \ �ֶ�����
		public static final int UDRM_ERROR_LICENSE_NOT_EXIST = -35; //License is not exist \ ���֤������
		public static final int UDRM_ERROR_LICENSE_INVALID = -36; //License is invalid \ ���֤��Ч
		public static final int UDRM_ERROR_LICENSE_UPDATE = -37; //License need update \ ���֤�����
		public static final int UDRM_ERROR_LICENSE_EXPIRATION = -38; //License is expiration \ ���֤�ѹ���
		public static final int UDRM_ERROR_CERTREQ_HAVE_NO_DEAL = -39; //Exist no deal cert request \ ����δ�����֤������
		public static final int UDRM_ERROR_DB_CONNECT_ERROR = -40; //Connect database error \ ��ݿ������쳣
		public static final int UDRM_ERROR_DB_OPERATE_ERROR = -41; //Operate database error \ ��ݿ�����쳣
		public static final int UDRM_ERROR_ROOT_CERT_ERROR = -42; //Root ca error \ ��֤���쳣
		public static final int UDRM_ERROR_ROOT_PKEY_ERROR = -43; //Root private key error \ ��˽Կ�쳣
		public static final int UDRM_ERROR_GEN_CERT_ERROR = -44; //Genereate cert error \ ���֤���쳣
		public static final int UDRM_ERROR_MALLOC_ERROR = -45; //Malloc or new error \ ������Դ�쳣
		public static final int UDRM_ERROR_DEVICE_OPERATE_ERROR = -46; //Operate device error \ �豸�����쳣
		public static final int UDRM_ERROR_MY_CERT_ERROT = -47; //Get myself cert error \ �豸֤���쳣
		public static final int UDRM_ERROR_SOAP_GEN_PAR_ERROR = -48; //Generate soap parameter error \ SOAP�������
		public static final int UDRM_ERROR_SOAP_GEN_REQUEST_ERROR = -49; //Generate soap request error \ SOAP�����쳣
		public static final int UDRM_ERROR_SOAP_PARSE_RESPONSE_ERROR = -50; //Parse soap response error \ SOAP��Ӧ�����쳣
		public static final int UDRM_ERROR_HTTP_REQUEST_ERROR = -51; //Http request error \ ����ʧ��
		public static final int UDRM_ERROR_GEN_PKEY_ERROR = -52; //Generate private key error \ ���˽Կ�쳣
		public static final int UDRM_ERROR_GEN_CERTREQ_ERROR = -53; //Generate cert request error \ ���֤�������쳣
		public static final int UDRM_ERROR_DEVICE_NO_RIGHT = -54; //Device no right \ �豸��Ȩ��
		public static final int UDRM_ERROR_CERT_TYPE_INVALID = -55; //Cert type invalid \ ֤��������Ч
		public static final int UDRM_ERROR_BOSS_CONTENT_NOT_EXIST = -56; //BOSS content not exist \ BOSSϵͳ���ݲ�����
		public static final int UDRM_ERROR_BOSS_DEVICE_NOT_EXIST = -57; //BOSS device not exist \ BOSSϵͳ�豸������
		public static final int UDRM_ERROR_BOSS_DEVICE_INVALID = -58; //BOSS device invalid \ BOSSϵͳ�豸��Ч
		public static final int UDRM_ERROR_BOSS_DEVICE_NO_RIGHT = -59; //BOSS device no right \ BOSSϵͳ�豸��Ȩ��
		public static final int UDRM_ERROR_BOSS_CREDIT_NOT_ENOUGH = -60; //BOSS device not enough credit \ BOSSϵͳ�ʽ���
		public static final int UDRM_ERROR_BOSS_CONTENT_NO_RIGHT = -61; //BOSS content no right \ BOSSϵͳ������Ȩ��
		public static final int UDRM_ERROR_BOSS_OPERATE_ERROR = -62; //BOSS operate error \ BOSSϵͳ�����쳣
		public static final int UDRM_ERROR_SEND_ERROR = -63; //Send data error \ ��������쳣
		public static final int UDRM_ERROR_RECV_ERROR = -64; //Receive data error \ ��������쳣
		public static final int UDRM_ERROR_SSL_NEW_ERROR = -65; //SSL new error \ ����SSLʧ��
		public static final int UDRM_ERROR_SSL_USE_CERT_ERROR = -66; //SSL use cert error \ SSL����֤���쳣
		public static final int UDRM_ERROR_SSL_USE_PKEY_ERROR = -67; //SSL use private key error \ SSL����˽Կ�쳣
		public static final int UDRM_ERROR_SSL_CONNECT_ERROR = -68; //SSL connect error \ SSL����ʧ��
		public static final int UDRM_ERROR_SSL_SERVER_CERT_INVALID = -69; //SSL server cert check error \ SSL������֤��У�����
		public static final int UDRM_ERROR_TIMESTAMP_ERROR = -70; //Timestamp invalid \ ʱ�������
		public static final int UDRM_ERROR_SIGNATURE_CERT_NO_TRUST = -71; //Certificate used for the signature is not trusted \ ֤�鲻����
		public static final int UDRM_ERROR_SIGNATURE_PROCESS_ERROR = -72; //Security processing failed \ ǩ�����쳣
		public static final int UDRM_ERROR_CERTNAME_EXIST = -73; //Cert name already exist \ ֤������Ѵ���
		public static final int UDRM_ERROR_MY_PKEY_ERROR = -74; //Load private key error \ �豸˽Կ����
		public static final int UDRM_ERROR_LOAD_CERT_ERROR = -75; //Load cert or cert link error \ ����֤�����
		public static final int UDRM_ERROR_SSL_CERT_ERROR = -76; //SSL connect cert error \ SSL֤�����
		public static final int UDRM_ERROR_SSL_PKEY_ERROR = -77; //SSL connect pkey error \ SSL˽Կ����
		public static final int UDRM_ERROR_DEVICE_ID_ERROR = -78; //Device id error \ DRM�豸ID������豸������
		public static final int UDRM_ERROR_DEVICE_TYPE_ERROR = -79; //Device type error \ DRM�豸���ʹ���
		public static final int UDRM_ERROR_DEVICE_NO_INIT = -80; //Device no initial \ DRM�豸δ��ʼ��
		public static final int UDRM_ERROR_DEVICE_BIND_NOT_MATCH = -81; //Device bind not match \ DRM�豸�󶨲�ƥ��
		public static final int UDRM_ERROR_BOSS_USERID_ERROR = -82; //BOSS user id error \ BOSSϵͳ�û�������
		public static final int UDRM_ERROR_BOSS_PASSWORD_ERROR = -83; //BOSS user password error \ BOSSϵͳ�û��������
		public static final int UDRM_ERROR_DEVICE_USER_ERROR = -84; //Device user error \ DRM�豸�û���ƥ��
		public static final int UDRM_ERROR_DEVICE_MAC_ERROR = -85; //Device mac error \ DRM�豸���ն�MAC��ƥ��
		public static final int UDRM_ERROR_BOSS_USER_NO_RIGHT = -86; //BOSS user no right \ BOSSϵͳ�û���Ȩ��
		public static final int UDRM_ERROR_BOSS_BIND_NUM_OVER = -87; //BOSS bind number over \ BOSSϵͳ����Ŀ����
		public static final int UDRM_ERROR_BOSS_NO_RIGHT = -88; //BOSS no right \ BOSSϵͳ��Ȩ��
		public static final int UDRM_ERROR_BOSS_NOT_SUPPORT = -89; //BOSS not support \ BOSSϵͳ��֧��
		public static final int UDRM_ERROR_BOSS_BIND_ERROR = -90; //BOSS bind error \ BOSSϵͳ���쳣
		public static final int UDRM_ERROR_BOSS_USERID_ALREADY_EXIST = -91; //BOSS user id already exist \ BOSSϵͳ�û�ID�Ѵ���
		public static final int UDRM_ERROR_BOSS_USER_DEVICE_NOT_MATCH = -92; //BOSS user device not match \ BOSSϵͳ�û��豸��ƥ��
		public static final int UDRM_ERROR_BOSS_VALIDATION_ERROR = -93; //BOSS validation error \ BOSSϵͳ��֤�����
		public static final int UDRM_ERROR_BOSS_DEVICE_ID_ALREADY_EXIST = -94; //BOSS device id already exist \ BOSSϵͳDRM�豸ID�Ѵ���
		public static final int UDRM_ERROR_BOSS_DEVICE_TYPE_ERROR = -95; //BOSS device type error \ BOSSϵͳDRM�豸���ʹ���
		public static final int UDRM_ERROR_BOSS_DEVICE_ALREADY_REGISTER = -96; //BOSS device already register \ BOSSϵͳDRM�豸��ע��
		public static final int UDRM_ERROR_BOSS_DEVICE_ALREADY_BIND = -97; //BOSS device already bind \ BOSSϵͳDRM�豸�Ѱ�
		public static final int UDRM_ERROR_BOSS_CONTENT_ID_ALREADY_EXIST = -98; //BOSS content id already exist \ BOSSϵͳ����ID�Ѵ���
		public static final int UDRM_ERROR_BOSS_DB_OPERATE_ERROR = -99; //BOSS db operate error \ BOSSϵͳ��ݿ�����쳣
		public static final int UDRM_ERROR_BOSS_SERVICE_CONNECT_ERROR = -100; //BOSS service connect error \ BOSSϵͳ���������쳣
		public static final int UDRM_ERROR_BOSS_SERVICE_OPERATE_ERROR = -101; //BOSS service operate error \ BOSSϵͳ��������쳣
		public static final int UDRM_ERROR_BOSS_LICENSE_ID_ERROR = -102; //BOSS license id error \ BOSSϵͳ���֤ID��������֤������
		public static final int UDRM_ERROR_BOSS_USER_NOT_MATCH = -103; //BOSS user not match \ BOSSϵͳ�û���ƥ��
		public static final int UDRM_ERROR_LICENSE_PLAYCOUNT_OVER = -104; //License play count over \ ���֤���Ŵ�����
		public static final int UDRM_ERROR_LICENSE_PLAYTIME_OVER = -105; //License play time over \ ���֤����ʱ�䳬��
		public static final int UDRM_ERROR_LICENSE_PLAYPERIOD_OVER = -106; //License play period over \ ���֤����ʱ��γ���
		public static final int UDRM_ERROR_LICENSE_HMAC_ERROR = -107; //License HMAC error \ ���֤У�����
		public static final int UDRM_ERROR_LICENSE_TIME_INVALID = -108; //License time invalid \ ���֤ʱ����Ч
		public static final int UDRM_ERROR_LICENSE_CHECK_TIME_OVER = -109; //License check time over \ ���֤���ʱ�䳬��
		public static final int UDRM_ERROR_LICENSE_CONTENT_NOT_MATCH = -110; //License content not match \ ���֤���ݲ�ƥ��
		public static final int UDRM_ERROR_URL_ERROR = -111; //URL error \ URL��ַ�쳣
		public static final int UDRM_ERROR_PROTOCOL_ERROR = -112; //Protocol error \ Э�����
		public static final int UDRM_ERROR_HOSTNAME_ERROR = -113; //Host name error \ HOST NAME����
		public static final int UDRM_ERROR_BAD_REQUEST = -114; //400 Bad Request \ HTTP 400����
		public static final int UDRM_ERROR_SERVICE_TEMP_UNAVAILABLE = -115; //503 Service Temporarily Unavailable \ HTTP 503����
		public static final int UDRM_ERROR_USERID_EMPTY = -116; //User id is empty \ �û�IDΪ��
		public static final int UDRM_ERROR_PASSWORD_EMPTY = -117; //Password is empty \ ����Ϊ��
		public static final int UDRM_ERROR_AGENT_SERVER_TIME_ERROR = -118; //Get agent server time error \ ��ȡ������ʱ���쳣
		public static final int UDRM_ERROR_GROUP_ID_ERROR = -119; //Group id error \ ��ID����
		public static final int UDRM_ERROR_GROUP_ID_NOT_EXIST = -120; //Group id not exist \ �鲻����
		public static final int UDRM_ERROR_GROUP_ID_ALREADY_EXIST = -121; //Group id already exist \ ��ID�Ѿ�����
		public static final int UDRM_ERROR_GROUP_NO_RIGHT = -122; //Group no right \ ����Ȩ��
		public static final int UDRM_ERROR_GROUP_NUM_OVER = -123; //Group number over \ ����������
		public static final int UDRM_ERROR_GROUP_CERT_ERROR = -124; //Group cert error \ ��֤�����
		public static final int UDRM_ERROR_GROUP_PKEY_ERROR = -125; //Group private key error \ ��˽Կ����
		public static final int UDRM_ERROR_DEVICE_FILE_ERROR = -126; //Device file error \ �豸�ļ�����
		public static final int UDRM_ERROR_DEVICE_FILE_OPEN_ERROR = -127; //Device file open error \ �豸�ļ����쳣
		public static final int UDRM_ERROR_DEVICE_FILE_READ_ERROR = -128; //Device file read error \ �豸�ļ���ȡ�쳣
		public static final int UDRM_ERROR_DEVICE_FILE_WRITE_ERROR = -129; //Device file write error \ �豸�ļ�д���쳣
		public static final int UDRM_ERROR_DEVICE_FILE_CLOSE_ERROR = -130; //Device file close error \ �豸�ļ��ر��쳣
		public static final int UDRM_ERROR_DEVICE_DATA_TYPE_ERROR = -131; //Device data type error \ �豸������ʹ���
		public static final int UDRM_ERROR_RULE_NOT_EXIST = -132; //Rule is not exist \ ʹ�ù��򲻴���
		public static final int UDRM_ERROR_RULE_ALREADY_EXIST = -133; //Rule already exist \ ʹ�ù����Ѿ�����
		public static final int UDRM_ERROR_RULE_INVALID = -134; //Rule is invalid \ ʹ�ù�����Ч
		public static final int UDRM_ERROR_RULE_UPDATE = -135; //Rule need update \ ʹ�ù��������
		public static final int UDRM_ERROR_RULE_EXPIRATION = -136; //Rule is expiration \ ʹ�ù����ѹ���
		public static final int UDRM_ERROR_GZIP_ERROR = -137; //Gzip error \ GZIP�쳣
		public static final int UDRM_ERROR_GZIP_NOT_SUPPORT = -138; //Gzip not support \ GZIP��֧��
		public static final int UDRM_ERROR_ENV_ERROR = -139; //Env value error \ ��������ֵ����
		public static final int UDRM_ERROR_ENV_EMPTY = -140; //Env is empty \ ��������Ϊ��
		public static final int UDRM_ERROR_NOT_MATCH = -141; //Information not match \ ��Ϣ��ƥ��
		public static final int UDRM_ERROR_PARSE_XML_ERROR = -142; //parse xml error \ ����XML�쳣
		public static final int UDRM_ERROR_SYNC_EVENT_ERROR = -143; //sync event error \ �¼�ͬ���쳣
		public static final int UDRM_ERROR_BOSS_UNBIND_ERROR = -144; //boss unbind error \ BOSS������
		public static final int UDRM_ERROR_BOSS_NOTBIND_ERROR = -145; //boss not bind \ BOSSδ��
		public static final int UDRM_ERROR_BOSS_URL_ERROR = -146; //boss url error \ BOSS URL����
		public static final int UDRM_ERROR_TRANSFER_CERT_ERROR = -147; //transfer cert error \ ת��֤���쳣
		public static final int UDRM_ERROR_REQUEST_CERT_ERROR = -148; //request cert error \ ����֤���쳣
		public static final int UDRM_ERROR_CONTENT_NO_RIGHT = -149; //content no right \ ������Ȩ��
		public static final int UDRM_ERROR_BIND_ERROR = -150; //bind error \ ���쳣
		public static final int UDRM_ERROR_UNBIND_ERROR = -151; //unbind error \ ����쳣
		public static final int UDRM_ERROR_NOT_BIND_ERROR = -152; //not bind error \ δ��
		public static final int UDRM_ERROR_VERSION_ERROR = -153; // Version error \ �汾����
		public static final int UDRM_ERROR_VERSION_NOT_SUPPORT = -154; // Version not support \ �汾��֧��
		public static final int UDRM_ERROR_VERSION_NEED_UPDATE = -155; // Version need update \ �汾�����
		public static final int UDRM_ERROR_TRANSFER_DCERT_NOT_MATCH = -156; // Transfer device cert not match \ �����豸֤�鲻ƥ��
		public static final int UDRM_ERROR_NEED_BIND = -157; // Need bind \ ��Ҫ��
		
		
		//drm stage	
		public static final int UDRM_STAGE_NONE = 0;
		public static final int UDRM_STAGE_DRM_AGENT_CERT_NOT_FOUND = 1;//CERT INIT
		public static final int UDRM_STAGE_DRM_AGENT_CERT_INIT_START = 2;
		public static final int UDRM_STAGE_DRM_AGENT_CERT_INITINIZING = 3;
		public static final int UDRM_STAGE_DRM_AGENT_CERT_INIT_SUCCESS = 4;
		public static final int UDRM_STAGE_DRM_AGENT_CERT_INIT_FAILED = 5;
		public static final int UDRM_STAGE_DRM_AGENT_CERT_INVALID_FOUND = 6;//CERT UPDATE
		public static final int UDRM_STAGE_DRM_AGENT_CERT_UPDATE_START = 7;
		public static final int UDRM_STAGE_DRM_AGENT_CERT_UPDATING = 8;
		public static final int UDRM_STAGE_DRM_AGENT_CERT_UPDATE_SUCCESS = 9;
		public static final int UDRM_STAGE_DRM_AGENT_CERT_UPDATE_FAILED = 10;
		public static final int UDRM_STAGE_DRM_AGENT_INIT_START = 11;//AGENT INIT
		public static final int UDRM_STAGE_DRM_AGENT_INIT_SUCCESS = 12;
		public static final int UDRM_STAGE_DRM_AGENT_INIT_FAILED = 13;
		public static final int UDRM_STAGE_DRM_CONTENT_FOUND = 14;
		public static final int UDRM_STAGE_START_ACCESS_LICENSE = 15;//LICENSE ACCESS
		public static final int UDRM_STAGE_DRM_SESSION_CREATED = 16;
		public static final int UDRM_STAGE_DRM_SESSION_CREATE_FAILED = 17; 
		public static final int UDRM_STAGE_ACCESSING_LICENSE = 18;
		public static final int UDRM_STAGE_ACCESS_LICENSE_FAILED_RETRY = 19;
		public static final int UDRM_STAGE_ACCESS_LICENSE_SUCCESS = 20;
		public static final int UDRM_STAGE_ACCESS_LICENSE_FAILED = 21;
		public static final int UDRM_STAGE_DRM_SESSION_CLOSED = 22;
		public static final int UDRM_STAGE_DRM_AGENT_DESTORY = 23;
		
		//drm error
		public static final int  UDRM_AGENT_ERROR_OK =     0;   /*�޴���*/
		public static final int  UDRM_AGENT_CERT_ERROR =    -1;   /*֤�����*/
		public static final int  UDRM_AGENT_NETWORK_ERROR =    -2;   /*�������*/
		public static final int  UDRM_AGENT_AUTHORIZATION_ERROR =    -3;   /*��Ȩ����*/
		public static final int  UDRM_AGENT_SYSTEM_ERROR =    -4;   /*ϵͳ����*/
}
